// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgWEMGqI5xf84dKO8ENmX_k3RZlOzd2ak',
    appId: '1:897178056735:web:ba99ca86f7a1a08bd4fd2a',
    messagingSenderId: '897178056735',
    projectId: 'finance-app-cb29b',
    authDomain: 'finance-app-cb29b.firebaseapp.com',
    storageBucket: 'finance-app-cb29b.firebasestorage.app',
    measurementId: 'G-PGSWLRKB3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKVZn0UFytVJV3m9TESQLltSg1_RSTqaE',
    appId: '1:897178056735:android:e86f42d803ee4fd5d4fd2a',
    messagingSenderId: '897178056735',
    projectId: 'finance-app-cb29b',
    storageBucket: 'finance-app-cb29b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9fnTrPizeG46Bb0QhLnLaHWlXgt_CLfI',
    appId: '1:897178056735:ios:249f52125241e20fd4fd2a',
    messagingSenderId: '897178056735',
    projectId: 'finance-app-cb29b',
    storageBucket: 'finance-app-cb29b.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9fnTrPizeG46Bb0QhLnLaHWlXgt_CLfI',
    appId: '1:897178056735:ios:249f52125241e20fd4fd2a',
    messagingSenderId: '897178056735',
    projectId: 'finance-app-cb29b',
    storageBucket: 'finance-app-cb29b.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgWEMGqI5xf84dKO8ENmX_k3RZlOzd2ak',
    appId: '1:897178056735:web:d4e026cfdf09de36d4fd2a',
    messagingSenderId: '897178056735',
    projectId: 'finance-app-cb29b',
    authDomain: 'finance-app-cb29b.firebaseapp.com',
    storageBucket: 'finance-app-cb29b.firebasestorage.app',
    measurementId: 'G-XXN91632VW',
  );
}
